### PR TITLE
Update to dhall-1.26.1

### PR DESCRIPTION
**Pull request by jneira**
Tested manually with https://github.com/jneira/eta-test/tree/test-dhall

### CODE REVIEW

**Comment by rahulmutt** [comment]
Looks good @jneira! The CircleCI build seems to be failing - can you take a look?

**Comment by jneira** [comment]
It is failing cause it is not updating the dhall-to-etlas submodule to the actual commit but the old one :thinking:

**Comment by jneira** [comment]
I dont understand why it is checking out the `dhall-to-etlas` master commit instead the new one, in local it works as expected:
```
D:\ws\eta\pkgs>git clone https://github.com/jneira/etlas.git -b dhall-1.26.1
Cloning into 'etlas'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 3367 (delta 9), reused 21 (delta 9), pack-reused 3341
Receiving objects: 100% (3367/3367), 1.82 MiB | 3.72 MiB/s, done.
Resolving deltas: 100% (2161/2161), done.
Checking out files: 100% (352/352), done.

D:\ws\eta\pkgs>cd etlas

D:\ws\eta\pkgs\etlas>git status
On branch dhall-1.26.1
Your branch is up to date with 'origin/dhall-1.26.1'.

nothing to commit, working tree clean

D:\ws\eta\pkgs\etlas>git submodule sync

D:\ws\eta\pkgs\etlas>git submodule update --init --recursive
Submodule 'dhall-to-etlas' (https://github.com/eta-lang/dhall-to-etlas) register
ed for path 'dhall-to-etlas'
Submodule 'hackage-security' (https://github.com/Jyothsnasrinivas/hackage-securi
ty.git) registered for path 'hackage-security'
Cloning into 'D:/ws/eta/pkgs/etlas/dhall-to-etlas'...
Cloning into 'D:/ws/eta/pkgs/etlas/hackage-security'...
Submodule path 'dhall-to-etlas': checked out 'cfcf1d2318c4f3c5a9c589e960fd0677cc
440f20'
Submodule path 'hackage-security': checked out 'f12981117bee9a6deaba799f24ecbd7f
84e09327'
```

But in circleci:

```
#!/bin/bash -eo pipefail
git submodule update --init --recursive
Submodule 'dhall-to-etlas' (https://github.com/eta-lang/dhall-to-etlas) registered for path 'dhall-to-etlas'
Submodule 'hackage-security' (https://github.com/Jyothsnasrinivas/hackage-security.git) registered for path 'hackage-security'
Cloning into '/root/etlas/dhall-to-etlas'...
Cloning into '/root/etlas/hackage-security'...
Submodule path 'dhall-to-etlas': checked out '7ebf6be359d1957063deeaeb2cff8618402cdc8b'
Submodule path 'hackage-security': checked out 'f12981117bee9a6deaba799f24ecbd7f84e09327'
```

**Comment by jneira** [comment]
@rahulmutt ci is happy! i had to change the way circleci does the submodule updates :-/

**Pull request closed without merging**
